[sync_reader]
cluster = false
address = "${SHAKE_SRC_ADDRESS}"
username = "${SHAKE_SRC_USERNAME}"
password = "${SHAKE_SRC_PASSWORD}"
tls = false
sync_rdb = true
sync_aof = true

[redis_writer]
cluster = false
address = "${SHAKE_DST_ADDRESS}"
username = "${SHAKE_DST_USERNAME}"
password = "${SHAKE_DST_PASSWORD}"
tls = true
