[scan_reader]
cluster = false
address = "${SHAKE_SRC_ADDRESS}"
username = "${SHAKE_SRC_USERNAME}"
password = "${SHAKE_SRC_PASSWORD}"
tls = false

# optional selectors / tuning
dbs = []
scan = true
ksn = false
count = 10

[redis_writer]
cluster = false
address = "${SHAKE_DST_ADDRESS}"
username = "${SHAKE_DST_USERNAME}"
password = "${SHAKE_DST_PASSWORD}"
tls = true
